FROM python:3.10

LABEL maintainer="agmc22mx@gmail.com"
LABEL version="1.0"
 
WORKDIR /app

RUN apt-get update 

# hadolint ignore=DL3008
RUN apt-get install -y curl install -y python3 python3-pip && pip3 install --no-cache-dir pyyaml==1.1
 
COPY testing.py ./

CMD ["python", "testing.py"]